### ISSUE TITLE
Identify recall datasets

### ISSUE THREAD

**Issue by aronwc** [tapilab/is-shreeshbhat#3]
@shreeshbhat  You've found two so far:
- http://www.cpsc.gov/en/Recalls/CPSC-Recalls-Application-Program-Interface-API-Information/
- http://www.fda.gov/Safety/Recalls/ArchiveRecalls/default.htm

Have you also looked at this one?
- https://www.recalls.gov

**Comment by shreeshbhat** [comment]
@aronwc : Looked into recalls.gov today. 

I m not able to find the recall data in http://www3.epa.gov/ for pesticides.

Food related Recalls : ( Not in a structured format )
http://www.fsis.usda.gov/wps/portal/fsis/topics/recalls-and-public-health-alerts/recall-case-archive


Car Recalls:
http://www-odi.nhtsa.dot.gov/downloads/

Boat Recalls:
http://uscgboating.org/content/recalls.php

---------------------------------------------

Car review dataset from Edmunds.com:
http://kavita-ganesan.com/entity-ranking-data
Model years : 2007 - 2009 
Size :  ~42,000+ reviews

Amazon review data :
http://jmcauley.ucsd.edu/data/amazon/
Date range :  May 1996 - July 2014
Need to request : Julian McAuley (julian.mcauley@gmail.com) to obtain download link.
