### ISSUE TITLE
download related work pdfs

### ISSUE THREAD

**Issue by aronwc** [tapilab/is-shreeshbhat#4]
see RelatedWork.md

**Comment by aronwc** [comment]
@shreeshbhat 

Looking more closely, I don't think many of these papers are very relevant. Here is a link to one of them:

Product safety and security in the global supply chain: Issues, challenges and research opportunities

<https://dspace.lib.cranfield.ac.uk/bitstream/1826/7690/1/Product_safety_and_security.pdf>

And here are a couple others that are related:

- <http://aldservice.com/images/stories/articles_pdf/2015-01-0487.pdf>
- This one predicts product recalls based on market information: <http://carlsonschool.umn.edu/file/60021/download?token=HMu_2UhG>

**Comment by shreeshbhat** [comment]
@aronwc : 
Yeah, I had mentioned at first that I couldn't find many related papers.
Will look into these. Could you please let me know how you found them too, so that I can search in a similar way?

**Comment by aronwc** [comment]
@shreeshbhat 
I think I searched on Google Scholar for "predict product recall" and variants therein.
